% Filters
clearvars; 

% Input files
rootdir = '\\XXX\ActionPrediction\data\brainstorm_database\ActionPrediction\data\';
cd(rootdir);
subs = {'XXXX','YYYY'};%... etc ...
for isub = 1:2

    sub = subs{isub};
    runfolders = dir([rootdir sub filesep '*@raw*']);
    sFiles = cell(1,length(runfolders));
    for irun=1:length(runfolders)
        runfile = dir([rootdir sub filesep runfolders(irun).name filesep '*raw*']);
        sFiles{1,irun} = [sub filesep runfolders(irun).name filesep runfile.name];
    end

    % Start a new report
    bst_report('Start', sFiles);

    % Process: Notch filter: 50Hz 100Hz
    sFiles = bst_process('CallProcess', 'process_notch', sFiles, [], ...
        'sensortypes', 'MEG, EEG', ...
        'freqlist',    [50, 100], ...
        'cutoffW',     0.5, ...
        'useold',      0, ...
        'read_all',    0);

    % Process: Resample: 500Hz
    sFiles = bst_process('CallProcess', 'process_resample', sFiles, [], ...
        'freq',     500, ...
        'read_all', 0);

    % Process: Power spectrum density (Welch)
    sFiles = bst_process('CallProcess', 'process_psd', sFiles, [], ...
        'timewindow',  [], ...
        'win_length',  1, ...
        'win_overlap', 50, ...
        'sensortypes', 'MEG', ...
        'win_std',     0, ...
        'edit',        struct(...
             'Comment',         'Power', ...
             'TimeBands',       [], ...
             'Freqs',           [], ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'SaveKernel',      0));

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);

end
