% Run ICA surrounding blinks events
% 2 times: separately for MAG and GRAG, blinks are ordered according to
% correlation with EOG
clearvars;

% Input files
rootdir = '\\XXX\ActionPrediction\data\brainstorm_database\ActionPrediction\data\';
cd(rootdir);

subs = {'XXXX','YYYY'};% ... etc ...
for isub = 1:2
    
    sub = subs{isub};
    
    runfolders = dir([rootdir sub filesep '*resample*']);
    sFiles = cell(1,length(runfolders));
    for irun=1:length(runfolders)
        runfile = dir([rootdir sub filesep runfolders(irun).name filesep '*raw*']);
        sFiles{1,irun} = [sub filesep runfolders(irun).name filesep runfile.name];
    end

    % different EOG channels were used for different subjects, as the entrance for the EOG channels in the MSR was falling apart...
    if strcmp(sub,'XXXX')   
        EOGchan = 'EEG062';
    elseif strcmp(sub,'YYYY') 
        EOGchan = 'EEG063';
    elseif strcmp(sub,'ZZZZ')
        EOGchan = 'EEG064';
    end
    
    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: ICA components: Infomax
    sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
        'timewindow',   [], ...
        'eventname',    '', ...
        'eventtime',    [-0.2, 0.2], ...%ignore if no eventname
        'resample',     250, ...
        'bandpass',     [0.1, 100], ...
        'nicacomp',     20, ...
        'sensortypes',  'MEG MAG', ...
        'icasort',      EOGchan, ...
        'usessp',       1, ...
        'ignorebad',    1, ...
        'saveerp',      0, ...
        'method',       1);  % Infomax:    EEGLAB / RunICA
    
    % Process: ICA components: Infomax
    sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
        'timewindow',   [], ...
        'eventname',    '', ...
        'eventtime',    [-0.2, 0.2], ...%ignore if no eventname
        'resample',     250, ...
        'bandpass',     [0.1, 100], ...
        'nicacomp',     20, ...
        'sensortypes',  'MEG GRAD', ...
        'icasort',      EOGchan, ...
        'usessp',       1, ...
        'ignorebad',    1, ...
        'saveerp',      0, ...
        'method',       1);  % Infomax:    EEGLAB / RunICA
    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
end
